Iqiyi\AvonBundle\Entity\AvonSubject:
    type: entity
    table: avon_subject
    id:
        subjectId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: subject_id
            generator:
                strategy: IDENTITY
    fields:
        memName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 联系人姓名
            default: ''
            column: mem_name
        memGender:
            type: boolean
            nullable: false
            comment: '联系人性别 0.男 1.女'
            default: '0'
            column: mem_gender
        memMobile:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: 联系手机
            default: ''
            column: mem_mobile
        content:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: '最美一瞬内容'
            default: ''
        addTime:
            type: integer
            nullable: false
            unsigned: false
            comment: 发布时间
            default: '0'
            column: add_time
        fromType:
            type: boolean
            nullable: false
            comment: '发布平台 0.pc 1.mobile'
            default: '0'
            column: from_type
    lifecycleCallbacks: {  }
