Iqiyi\AvonBundle\Entity\AvonPhoto:
    type: entity
    table: avon_photo
    id:
        photoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: photo_id
            generator:
                strategy: IDENTITY
    fields:
        memName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 联系人姓名
            default: ''
            column: mem_name
        memGender:
            type: boolean
            nullable: false
            comment: '联系人性别 0.男 1.女'
            default: '0'
            column: mem_gender
        memMobile:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: 联系手机
            default: ''
            column: mem_mobile
        memAddress:
            type: string
            nullable: false
            length: 120
            fixed: false
            comment: 地址
            default: ''
            column: mem_address
        memZip:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: 邮编
            default: ''
            column: mem_zip
        photoUrl:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: '照片地址'
            default: ''
            column: photo_url
        content:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: '最美一瞬内容'
            default: ''
        addTime:
            type: integer
            nullable: false
            unsigned: false
            comment: 发布时间
            default: '0'
            column: add_time
        status:
            type: boolean
            nullable: false
            comment: '审核状态 0.待审 1.通过'
            default: '0'
        totalVote:
            type: integer
            nullable: false
            unsigned: false
            comment: 得票总数
            default: '0'
            column: total_vote
    lifecycleCallbacks: 
        prePersist: [preUpload, upload]
        preUpdate: [preUpload, upload]
        postRemove: [removeUpload]
