security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    root: { password: FHGoadyiag5lb139, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    admin: { password: Goadyiag5, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
