security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    root: { password: FHGoadyiag5lb139, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    admin: { password: Goadyiag5, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        login_firewall:
            pattern:   ^/admin/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /admin/login
                check_path: /login_check
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /admin/login

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
