iqiyi_avon_homepage:
    pattern:  /home
    defaults: { _controller: IqiyiAvonBundle:Home:index }

iqiyi_avon_addphoto:
    pattern:  /addphoto
    defaults: { _controller: IqiyiAvonBundle:Home:addphoto }