iqiyi_avon_homepage:
    pattern:  /home
    defaults: { _controller: IqiyiAvonBundle:Home:index }

iqiyi_avon_addphoto:
    pattern:  /addphoto
    defaults: { _controller: IqiyiAvonBundle:Home:addphoto }

iqiyi_avon_addmsg:
    pattern:  /addmsg
    defaults: { _controller: IqiyiAvonBundle:Home:addmsg }

iqiyi_avon_votemsg:
    pattern:  /votemsg
    defaults: { _controller: IqiyiAvonBundle:Home:votemsg }

iqiyi_avon_generate_redeem:
    pattern:  /back/redeem/generate
    defaults: { _controller: IqiyiAvonBundle:Backend:generateRedeemCode }