iqiyi_avon_homepage:
    pattern:  /home
    defaults: { _controller: IqiyiAvonBundle:Home:index }

iqiyi_avon_addphoto:
    pattern:  /addphoto
    defaults: { _controller: IqiyiAvonBundle:Home:addphoto }

iqiyi_avon_addmsg:
    pattern:  /addmsg
    defaults: { _controller: IqiyiAvonBundle:Home:addmsg }

iqiyi_avon_votemsg:
    pattern:  /votemsg
    defaults: { _controller: IqiyiAvonBundle:Home:votemsg }

##############################################################

login:
    path:  /admin/login
    defaults: { _controller: IqiyiAvonBundle:Backend:login }

login_check:
    path:  /login_check

iqiyi_avon_generate_redeem:
    pattern:  /admin/redeem/generate
    defaults: { _controller: IqiyiAvonBundle:Backend:generateRedeemCode }

logout:
    path:   /logout
