iqiyi_avon_homepage:
    pattern:  /home
    defaults: { _controller: IqiyiAvonBundle:Home:index }

iqiyi_avon_addphoto:
    pattern:  /addphoto
    defaults: { _controller: IqiyiAvonBundle:Home:addphoto }

iqiyi_avon_addmsg:
    pattern:  /addmsg
    defaults: { _controller: IqiyiAvonBundle:Home:addmsg }

iqiyi_avon_votemsg:
    pattern:  /votemsg
    defaults: { _controller: IqiyiAvonBundle:Home:votemsg }

##############################################################

login:
    path:  /admin/login
    defaults: { _controller: IqiyiAvonBundle:Backend:login }

login_check:
    path:  /login_check

logout:
    path:   /logout

iqiyi_avon_generate_redeem:
    pattern:  /admin/redeem/generate
    defaults: { _controller: IqiyiAvonBundle:Backend:generateRedeemCode }

iqiyi_avon_subject_list:
    pattern:  /admin/subject/list/{page}
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectList, page: 1 }
    requirements:
        page:  \d+

iqiyi_avon_subject_approve:
    pattern:  /admin/subject/{id}/approve/{status}
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectApprove}
    requirements:
        id:  \d+
        statis: 0|1

iqiyi_avon_subject_remove:
    pattern:  /admin/subject/{id}/remove/
    defaults: { _controller: IqiyiAvonBundle:Backend:subjectRemove}
    requirements:
        id:  \d+

