parameters:
#    iqiyi_avon.example.class: Iqiyi\AvonBundle\Example

services:
#    iqiyi_avon.example:
#        class: %iqiyi_avon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
