parameters:
    iqiyi_avon.validator.entityexists.class: Iqiyi\AvonBundle\Validator\Constraints\EntityExistsValidator

services:
    iqiyi_avon.validator.entity_exists:
        class: %iqiyi_avon.validator.entityexists.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: iqiyi_avon.validator.entity_exists }